site_name: PULSE - Python Unified Library for Sensor Emulation
site_url: https://pulse-docs.example.com

repo_url: https://github.com/zenoxml/pulse
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Installation Guide: installation_guide.md
  - Contribution: contribution.md
  - Testing: testing.md
  - API Reference:
      - Data Exporter: docs/api/data_exporter.md
      - Radar Properties: api/radar_properties.md
      - Main: api/main.md
      - Model: api/model.md
      - Hardware opt: api/hardware_opt.md
  - Upcoming Features: upcoming_features.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    scheme: slate
    primary: teal
    accent: light-blue

markdown_extensions:
  - codehilite
  - toc
  - admonition
  - pymdownx.details
  - pymdownx.superfences
