site_name: PULSE - Python Unified Library for Sensor Emulation
site_url: https://pulse-docs.example.com

repo_url: https://github.com/zenoxml/pulse
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Installation Guide: installation_guide.md
  - Testing: testing.md
  - API Reference:
      - Data Exporter: api/data_export.md
      - Radar Properties: api/radar_properties.md
      - Main: api/main.md
      - Model: api/model.md
      - Hardware opt: api/hardware_opt.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    scheme: slate
    primary: teal
    accent: light-blue

markdown_extensions:
  - codehilite
  - toc
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_toc_entry: true
            rendering:
              show_signature_annotations: true
          setup_commands:
            - "import sys; sys.path.insert(0, 'src')"  # Add src to Python path

